Repository Code-the-Dream-School/ii-practicum-team-8-front, pull requests merged in 2025-05, with the labels that each got.

#15 fixed errors after merge
  package-lock.json
  src/App.jsx
  src/Components/Footer.jsx
  src/Components/Navbar.jsx
  src/Components/Search.jsx
  src/Pages/Login.jsx
  src/Pages/Signup.jsx
  src/pages/BookingCalendarPage.jsx
  src/pages/HotelsPage.jsx
Labels: Approved

#14 Forgot Password implementation
  package-lock.json
  src/App.jsx
  src/components/Authentication/ForgotPassword.jsx
  src/util/index.js
Labels: Approved

#16 added calendar crud
  src/App.jsx
  src/Components/alerts/ErrorAlert.jsx
  src/Components/alerts/SuccessAlert.jsx
  src/Components/booking/BookingForm.jsx
  src/Components/calendar/EventComponent.jsx
  src/Components/shared/DateField.jsx
  src/Components/shared/NumberInput.jsx
  src/Components/shared/PhotoGallery.jsx
  src/components/calendar/BigCalendar.jsx
  src/components/hotels/SearchHotels/KidsAgeFields.jsx
  src/components/hotels/SearchHotels/SearchHotels.jsx
  src/components/hotels/SearchHotels/TravelerInfoDialog.jsx
  src/components/loading/LoadingWrapper.jsx
  src/hooks/useCalendarApi.js
  src/hooks/useFetchBookingList.js
  src/pages/BookingCalendarPage.jsx
  src/util/apiCalendar.js
  src/util/index.js
Labels: Approved

#19 fix the bugs and clean the issue get started button
  src/App.jsx
  src/Components/Navbar.jsx
  src/Pages/Home.jsx
  src/Pages/Signup.jsx
Labels: Approved

#18 added book now page and refactor code
  src/App.jsx
  src/Components/Footer.jsx
  src/Pages/BookNow.jsx
  src/Pages/Login.jsx
  src/Pages/Signup.jsx
  src/Routers/ProtectedRoutes.jsx
  src/components/Authentication/Login.jsx
  src/components/Destination.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/alerts/ErrorAlert.jsx
  src/components/alerts/SuccessAlert.jsx
  src/components/booking/BookingForm.jsx
  src/components/calendar/BigCalendar.jsx
  src/components/calendar/BigCalendarToolbar.jsx
  src/components/calendar/EventComponent.jsx
  src/components/calendar/headers/WeekHeader.jsx
  src/components/loading/LoadingWrapper.jsx
  src/components/shared/DateField.jsx
  src/components/shared/NumberInput.jsx
  src/components/shared/PhotoGallery.jsx
  src/data/hotelPhotos.json
  src/hooks/useStorageState.js
  src/pages/About.jsx
  src/pages/BookNow.jsx
  src/pages/BookingCalendarPage.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/routers/ProtectedRoutes.jsx
Labels: Approved

#23 added lazy load for Book Now! and Calendar pages and made them protected
  src/App.jsx
  src/components/Authentication/Login.jsx
  src/components/Destination.jsx
  src/context/AuthContext.jsx
  src/layouts/MainLayout.jsx
  src/routers/ProtectedRoutes.jsx
Labels: Needs 1 Approve

#26 User page
  package-lock.json
  src/App.css
  src/components/Authentication/ForgotPassword.jsx
  src/components/Authentication/Login.jsx
  src/components/Authentication/SignUp.jsx
  src/components/Navbar.jsx
  src/pages/Home.jsx
Labels: 👉 Awaiting Review

#30 state travel plane details
  src/App.css
  src/App.jsx
  src/Pages/Travelplan.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
Labels: Approved

#36 Update travel plan UI
  src/App.css
  src/App.jsx
  src/components/booking/BookingForm.jsx
  src/components/planner/TravelPlanCard.jsx
  src/components/planner/UpdateTravelPlan.jsx
Labels: 👉 Awaiting Review

#39 Forgot password and Reset password integrated with backend
  src/App.jsx
  src/components/Authentication/ForgotPassword.jsx
  src/components/Authentication/Login.jsx
  src/components/Authentication/ResetPassword.jsx
  src/components/Authentication/SignUp.jsx
Labels: Approved

#40 Css improvements
  src/App.css
  src/App.jsx
  src/components/Footer.jsx
  src/pages/BookNow.jsx
  src/pages/Home.jsx
  src/pages/Travelplan.jsx
Labels: Approved

#31 Theme for dark and light mode
  src/App.css
  src/App.jsx
  src/components/Authentication/ForgotPassword.jsx
  src/components/Authentication/Login.jsx
  src/components/Authentication/ResetPassword.jsx
  src/components/Authentication/SignUp.jsx
  src/components/Navbar.jsx
  src/components/Toggle.jsx
  src/context/ThemeModeContext.jsx
  src/index.css
  src/layouts/MainLayout.jsx
  src/pages/Home.jsx
Labels: Approved

#45 normalize date and then get local
  src/components/calendar/BigCalendar.jsx
  src/components/planner/TravelPlanCard.jsx
Labels: Needs 1 Approve

#44 Added dark-mode
  src/App.css
Labels: Approved
