Repository Code-the-Dream-School/ii-practicum-team-8-front, pull requests merged in 2025-04, with the labels that each got.

#7 Created Signup Page
  .env
  package-lock.json
  src/App.jsx
  src/components/Authentication/SignUp.jsx
  src/util/index.js
Labels: 👉 Awaiting Mentor Review

#10 added search bar and overall improvements
  package-lock.json
  package.json
  src/components/hotels/FacilitiesList.jsx
  src/components/hotels/HotelCard/HotelCard.jsx
  src/components/hotels/PhotoGallery.jsx
  src/components/hotels/SearchHotels/AutocompleteLocation.jsx
  src/components/hotels/SearchHotels/DateField.jsx
  src/components/hotels/SearchHotels/KidsAgeFields.jsx
  src/components/hotels/SearchHotels/NumberInput.jsx
  src/components/hotels/SearchHotels/SearchHotels.jsx
  src/components/hotels/SearchHotels/TravelerInfoDialog.jsx
  src/data/Motel6IssaquashDetails.json
  src/data/Motel6IssaquashFacilities.json
  src/data/Motel6IssaquashOnMap.json
  src/data/Motel6IssaquashPhotos.json
  src/data/hotels.json
  src/hooks/useHotelsQuery.js
  src/pages/HotelDetailsPage.jsx
  src/pages/HotelsPage.jsx
  src/util/apiBooking.js
  src/util/dateUtils.js
Labels: Needs Revision(s)

#12 Added calendar feature that fetches data from backend
  .env
  package-lock.json
  package.json
  src/App.jsx
  src/components/calendar/BigCalendar.jsx
  src/components/calendar/BigCalendar.style.css
  src/components/calendar/BigCalendarToolbar.jsx
  src/components/calendar/headers/Header.styles.jsx
  src/components/calendar/headers/MonthHeader.jsx
  src/components/calendar/headers/WeekHeader.jsx
  src/components/error/ErrorAlert.jsx
  src/components/loading/LoadingWrapper.jsx
  src/hooks/useCalendarApi.js
  src/main.jsx
  src/pages/BookingCalendarPage.jsx
  src/pages/HotelsPage.jsx
  src/util/apiCalendar.js
  src/util/index.js
Labels: Approved
